all:
  hosts:
    wordpress:
      ansible_host: fail1.toddbooth.com
      ansible_user: bitnami
      # ansible_ssh_private_key_file: ~/.ssh/wordpress.pem
    localhost:
    server2:
      ansible_host: 192.168.1.102

