name: Tests for All WordPress multiple subsites and Canvas configuration
on:
  push:
    branches:
      - main

jobs:
  Test_WordPress_Canvas_Installation_Configuration:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set the Node.js version to 16.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: Print some information about the environment
        run: |
          echo "Running on $(uname -a)"
          echo "Current directory: $PWD"
          ls -l
        
      - name: Test DNS Server domain resolution
        if: false
        run: |
          # Execute the external script.sh file
          chmod +x ./test_dig_resolve_ip.sh
          ./test_dig_resolve_ip.sh

      - name: Test if Web site answers a ping request, but just send one ping request
        run: |
          # firewall is blocking ping to toddbooth.com, so we will fake it with google.com
          ping -c 1 -W 3 google.com

      - name: Test if Web site ports 80 and 443 are listening
        if: false
        run: |
          # Execute the external script.sh file
          chmod +x ./test_nc_wp_listen.sh
          ./test_nc_wp_listen.sh

      - name: Test is Web site is serving web pages on ports 80 and 443
        if: false
        run: |
          # Execute the external script.sh file
          chmod +x ./test_curl_website.sh
          ./test_curl_website.sh

      - name: Test Web sites' certificates
        if: false
        run: |
          # Execute the external script.sh file
          chmod +x ./test_curl_certificate.sh
          ./test_curl_certificate.sh

      - name: Test WordPress user names via Bash
        if: false
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_KEY: ${{ secrets.WP_KEY }}
        run: |
          chmod +x ./test_wordpress_users.sh
          ./test_wordpress_users.sh
                            
      - name: Test Canvas user names via Python
        if: false
        env:
          CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}
        run: |
          python test_canvas_users.py
                    
      - name: Test WordPress post via Python
        if: false
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_KEY: ${{ secrets.WP_KEY }}
        run: |
          python test_wordpress_post.py
            
      - name: Test WordPress page via Java
        if: false
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_KEY: ${{ secrets.WP_KEY }}
        run: |
          # version 11
          # java -version
          javac WordPressPageCreation.java
          java WordPressPageCreation

      - name: To get here, all tests have passed, so deployment will now begin
        run: |
          echo "All tests have passed, so deployment will now begin here ..."

          